# Generated by Django 3.1.1 on 2022-07-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(default=users.models.get_random_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', verbose_name='Mobile No.')),
                ('avtar', models.ImageField(blank=True, default='user_avtar_uploads/default.png', upload_to='user_avtar_uploads/', verbose_name='Avtar Image')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('role', models.SmallIntegerField(choices=[(1, 'Tutor'), (2, 'Student')], default=2, help_text='Choose User Role', verbose_name='Role')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_mail_sent', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All Users',
                'verbose_name_plural': 'All Users',
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='tutor_intro_videos/', verbose_name='Upload Intro Video')),
                ('charges', models.PositiveIntegerField(blank=True, default=100, help_text='Charges in INR', verbose_name='Charges per hour')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About Me')),
                ('qualification', models.TextField(blank=True, null=True, verbose_name='Qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
