# Generated by Django 3.1.1 on 2022-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Name'),
        ),
    ]
