# Generated by Django 3.1.1 on 2022-07-14 13:24

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0007_auto_20220714_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', verbose_name='Mobile No.')),
                ('avtar', models.ImageField(blank=True, default='tutor_avtar_uploads/default.png', upload_to='tutor_avtar_uploads/', verbose_name='Avtar Image')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='tutor_intro_videos/', verbose_name='Upload Intro Video')),
                ('charges', models.PositiveIntegerField(blank=True, default=100, help_text='Charges in INR', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Charges per hour')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About Me')),
                ('qualification', models.TextField(blank=True, null=True, verbose_name='Qualification')),
                ('days_avail', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], max_length=13, null=True, verbose_name='Days Available')),
                ('i_speak', models.ManyToManyField(blank=True, related_name='i_speak', to='language.LangLevel')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
