# Generated by Django 3.1.1 on 2022-07-15 13:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20220714_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='days_avail',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=27, null=True, verbose_name='Days Available'),
        ),
    ]
