# Generated by Django 3.1.1 on 2022-07-15 13:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20220715_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='days_avail',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], max_length=13, null=True, verbose_name='Days Available'),
        ),
    ]
