# Generated by Django 3.1.1 on 2022-07-16 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20220715_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='about_me',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Me'),
        ),
    ]
