# Generated by Django 3.1.1 on 2022-07-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20220716_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='intro_video',
            field=models.FileField(null=True, upload_to='tutor_intro_videos/', verbose_name='Upload Intro Video'),
        ),
    ]
