# Generated by Django 3.1.1 on 2022-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Site Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_data/', verbose_name='Site Logo')),
                ('icon', models.ImageField(blank=True, help_text='Only .png image accepted.', null=True, upload_to='site_data/', verbose_name='Site Icon')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
