# Generated by Django 3.1.1 on 2022-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(default='Site Title', max_length=500, verbose_name='Site Title'),
        ),
    ]
