# Generated by Django 3.1.1 on 2022-07-13 06:07

from django.db import migrations, models
import django.db.models.deletion
import language.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(default=language.models.get_random_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Language Name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LangLevel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(default=language.models.get_random_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Fluent'), (4, 'Native')], default=1, verbose_name='Select Level')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_level', to='language.language', verbose_name='Select Language')),
            ],
            options={
                'verbose_name': 'Language Level',
                'verbose_name_plural': 'Language Levels',
                'ordering': ['-created_on'],
            },
        ),
    ]
